### ISSUE TITLE
Get rid of global {$PUSHOVER.TOKEN} macro

### ISSUE THREAD

**Issue by i-ky** [v-zhuravlev/zbx_media_pushover#1]
Instead, use a placeholder (e.g. `<put your Pushover token here>`) in `token` parameter and instruct user to change it in media type *Description*.

I think it will make it easier to use your integration with multiple Pushover accounts within one Zabbix setup (import media type XML multiple times, set `token` for every one of them; no need to deal with global macro naming conflicts).

**Comment by v-zhuravlev** [comment]
Hi, thanks for the suggestion. 

Problem is, that once token is changed to user's - next XML export will export this token too. So user can accidentally share token to everyone, for example, when contributing/sharing.

At the same time, global macro is literally seen to every zabbix user. :)

**Comment by i-ky** [comment]
> So user can accidentally share token to everyone, for example, when contributing/sharing.

This should be easy to catch when reviewing diff. *Even if* this happens, the cool thing about tokens is that compromising them is not a big deal. You invalidate a compromised one and request a new one from the service.

> At the same time, global macro is literally seen to every zabbix user. :)

Indeed!
